### ISSUE TITLE
Unable to Parse JSON File

### ISSUE THREAD

**Issue by eduran0826** [getnamo/tensorflow-ue4#24]
Greetings,

I am fairly new to Unreal Engine. When I followed the instructions provided in the README, I simply dragged in the provided plugins and I receive the following error messages:

-------------------------
Running E:/UnrealEngineBuilds/UE_4.18/Engine/Binaries/DotNET/UnrealBuildTool.exe  -projectfiles -project="E:/UnrealProjects/NeuraSample/NeuraSample.uproject" -game -rocket -progress
Discovering modules, targets and source code for project...
ERROR: UnrealBuildTool Exception: Tools.DotNETCommon.JsonParseException: Unable to parse E:\UnrealProjects\NeuraSample\Plugins\socketio-client-ue4\._SocketIOClient.uplugin: Could not find token at index 0
          at Tools.DotNETCommon.JsonObject.Read(FileReference File)
          at UnrealBuildTool.PluginDescriptor.FromFile(FileReference FileName)
          at UnrealBuildTool.PluginInfo..ctor(FileReference InFile, PluginType InType)
          at UnrealBuildTool.Plugins.ReadPluginsFromDirectory(DirectoryReference ParentDirectory, PluginType Type)
          at UnrealBuildTool.Plugins.ReadProjectPlugins(DirectoryReference ProjectDirectory)
          at UnrealBuildTool.RulesCompiler.CreateProjectRulesAssembly(FileReference ProjectFileName)
          at UnrealBuildTool.ProjectFileGenerator.AddProjectsForAllTargets(List`1 AllGames, ProjectFile& EngineProject, ProjectFile& EnterpriseProject, Dictionary`2& GameProjects, Dictionary`2& ModProjects, Dictionary`2& ProgramProjects, Dictionary`2& TemplateGameProjects, Dictionary`2& SampleGameProjects)
          at UnrealBuildTool.ProjectFileGenerator.GenerateProjectFiles(String[] Arguments)
          at UnrealBuildTool.UnrealBuildTool.GuardedMain(String[] Arguments)
-----------------------

Has anyone encountered this and found a solution to the problem?

Thank you!

![failed_to_open](https://user-images.githubusercontent.com/12473592/39386359-dff55eb8-4a39-11e8-991d-c2ef174ce223.PNG)

**Comment by getnamo** [comment]
Which version of the releases (https://github.com/getnamo/tensorflow-ue4/releases) is giving you this problem? Are you clicking on the *.7z files and not the source?

**Comment by eduran0826** [comment]
I am utilizing tensorflow-ue4.19-v0.8.0-cpu.7z on Unreal Engine 4.18.3 on Windows 10.

Ah, as I was typing this I saw that it could be a compatibility issue I failed to see between the release I am using and my UE version.

**Comment by getnamo** [comment]
Yes, you should be using tensorflow-ue4.18-v0.7.0-cpu.7z for ue4.18

**Comment by getnamo** [comment]
did that fix your problem? if so kindly close the issue.

**Comment by eduran0826** [comment]
Yes that resolved the issue. A complete oversight from me. Thank you!
